name: PR Build

on:
  pull_request:
  
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Build
      run: dotnet run --project tools\DevOps.Tooling.Tool.Build\LanceC.DevOps.Tooling.Tool.Build.csproj
